name: CI/CD to Azure

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Build React
      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build
        shell: bash

      # 2) Move dist → root
      - name: Move build dist
        run: cp -r frontend/dist dist

      # 3) Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Zip everything
      - name: Zip artifact
        run: zip -r release.zip main.py requirements.txt dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}


      # (Optional) Configure startup command
      - name: Configure Azure Web App
        run: |
          az webapp config set \
            --name fastagentlmwebapp \
            --resource-group MyResourceGroup \
            --startup-file "gunicorn main:app -k uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fastagentlmwebapp'
          slot-name: 'Production'
          package: .
